export type PlantCategory =
  | "Small tree"
  | "Shrub"
  | "Flower"
  | "Grass"
  | "Groundcover"
  | "Vine";

export type YardPlant = {
  id: string;
  name: string;
  botanicalName: string;
  category: PlantCategory;
  height: string;
  spread: string;
  sun: string;
  water: "Low" | "Low–moderate" | "Moderate";
  season: string;
  color: string;
  markerColor: string;
  glyph: string;
  tags: string[];
};

export const yardPlants: YardPlant[] = [
  {
    id: "texas-redbud",
    name: "Texas redbud",
    botanicalName: "Cercis canadensis var. texensis",
    category: "Small tree",
    height: "15–20 ft",
    spread: "15–20 ft",
    sun: "Sun to part shade",
    water: "Low–moderate",
    season: "Pink spring bloom",
    color: "Pink",
    markerColor: "#b95476",
    glyph: "⌁",
    tags: ["spring color", "small tree", "pollinator"],
  },
  {
    id: "mexican-plum",
    name: "Mexican plum",
    botanicalName: "Prunus mexicana",
    category: "Small tree",
    height: "15–25 ft",
    spread: "15–20 ft",
    sun: "Sun to part shade",
    water: "Low–moderate",
    season: "White spring bloom",
    color: "White",
    markerColor: "#d6d0bc",
    glyph: "⌁",
    tags: ["spring color", "small tree", "wildlife"],
  },
  {
    id: "american-beautyberry",
    name: "American beautyberry",
    botanicalName: "Callicarpa americana",
    category: "Shrub",
    height: "4–6 ft",
    spread: "4–6 ft",
    sun: "Part shade",
    water: "Low–moderate",
    season: "Purple fall berries",
    color: "Purple",
    markerColor: "#76538e",
    glyph: "✤",
    tags: ["berries", "shade", "wildlife"],
  },
  {
    id: "coralberry",
    name: "Coralberry",
    botanicalName: "Symphoricarpos orbiculatus",
    category: "Shrub",
    height: "2–4 ft",
    spread: "3–6 ft",
    sun: "Part shade to shade",
    water: "Low",
    season: "Coral-red fall berries",
    color: "Coral",
    markerColor: "#b56f62",
    glyph: "✤",
    tags: ["low maintenance", "shade", "berries"],
  },
  {
    id: "black-eyed-susan",
    name: "Black-eyed Susan",
    botanicalName: "Rudbeckia hirta",
    category: "Flower",
    height: "1–3 ft",
    spread: "1–2 ft",
    sun: "Full sun",
    water: "Low",
    season: "Yellow summer bloom",
    color: "Yellow",
    markerColor: "#d8a723",
    glyph: "✦",
    tags: ["summer color", "pollinator", "low water"],
  },
  {
    id: "butterfly-milkweed",
    name: "Butterfly milkweed",
    botanicalName: "Asclepias tuberosa",
    category: "Flower",
    height: "1–2 ft",
    spread: "1–2 ft",
    sun: "Full sun",
    water: "Low",
    season: "Orange summer bloom",
    color: "Orange",
    markerColor: "#cb6f2d",
    glyph: "✦",
    tags: ["monarch host", "pollinator", "low water"],
  },
  {
    id: "mealy-blue-sage",
    name: "Mealy blue sage",
    botanicalName: "Salvia farinacea",
    category: "Flower",
    height: "2–3 ft",
    spread: "2–3 ft",
    sun: "Full sun",
    water: "Low",
    season: "Blue spring–fall bloom",
    color: "Blue",
    markerColor: "#526d9b",
    glyph: "✦",
    tags: ["long bloom", "pollinator", "low water"],
  },
  {
    id: "fall-aster",
    name: "Fall aster",
    botanicalName: "Symphyotrichum oblongifolium",
    category: "Flower",
    height: "2–3 ft",
    spread: "2–3 ft",
    sun: "Full sun",
    water: "Low",
    season: "Purple fall bloom",
    color: "Purple",
    markerColor: "#7560a5",
    glyph: "✦",
    tags: ["fall color", "pollinator", "low water"],
  },
  {
    id: "four-nerve-daisy",
    name: "Four-nerve daisy",
    botanicalName: "Tetraneuris scaposa",
    category: "Flower",
    height: "8–12 in",
    spread: "10–14 in",
    sun: "Full sun",
    water: "Low",
    season: "Yellow spring–fall bloom",
    color: "Yellow",
    markerColor: "#ddb733",
    glyph: "✦",
    tags: ["front of bed", "long bloom", "low water"],
  },
  {
    id: "little-bluestem",
    name: "Little bluestem",
    botanicalName: "Schizachyrium scoparium",
    category: "Grass",
    height: "2–4 ft",
    spread: "1.5–2 ft",
    sun: "Full sun",
    water: "Low",
    season: "Blue-green to copper",
    color: "Copper",
    markerColor: "#8e7b4a",
    glyph: "≋",
    tags: ["movement", "winter interest", "low water"],
  },
  {
    id: "inland-sea-oats",
    name: "Inland sea oats",
    botanicalName: "Chasmanthium latifolium",
    category: "Grass",
    height: "2–4 ft",
    spread: "2–3 ft",
    sun: "Part shade to shade",
    water: "Moderate",
    season: "Decorative seed heads",
    color: "Green",
    markerColor: "#6d8553",
    glyph: "≋",
    tags: ["shade", "movement", "natural style"],
  },
  {
    id: "sideoats-grama",
    name: "Sideoats grama",
    botanicalName: "Bouteloua curtipendula",
    category: "Grass",
    height: "1.5–3 ft",
    spread: "1.5–2 ft",
    sun: "Full sun",
    water: "Low",
    season: "Purple-tinted seed heads",
    color: "Green",
    markerColor: "#7f8951",
    glyph: "≋",
    tags: ["low water", "prairie texture", "wildlife"],
  },
  {
    id: "frogfruit",
    name: "Frogfruit",
    botanicalName: "Phyla nodiflora",
    category: "Groundcover",
    height: "3–6 in",
    spread: "3–6 ft",
    sun: "Sun to part shade",
    water: "Low–moderate",
    season: "White-purple warm-season bloom",
    color: "White",
    markerColor: "#8a9e74",
    glyph: "•",
    tags: ["groundcover", "pollinator", "lawn alternative"],
  },
  {
    id: "golden-groundsel",
    name: "Golden groundsel",
    botanicalName: "Packera obovata",
    category: "Groundcover",
    height: "1–2 ft",
    spread: "1–2 ft",
    sun: "Part shade to shade",
    water: "Low–moderate",
    season: "Yellow spring bloom",
    color: "Yellow",
    markerColor: "#c6a736",
    glyph: "•",
    tags: ["shade", "groundcover", "spring color"],
  },
  {
    id: "coral-honeysuckle",
    name: "Coral honeysuckle",
    botanicalName: "Lonicera sempervirens",
    category: "Vine",
    height: "8–15 ft",
    spread: "3–6 ft",
    sun: "Sun to part shade",
    water: "Low–moderate",
    season: "Coral spring–summer bloom",
    color: "Coral",
    markerColor: "#b8604b",
    glyph: "⌇",
    tags: ["trellis", "hummingbird", "long bloom"],
  },
];

export const plantPreferenceOptions = [
  "Low maintenance",
  "Low water",
  "Pollinator-friendly",
  "Evergreen structure",
  "Seasonal color",
  "Soft privacy",
];

export function describePlants(ids: string[]) {
  return ids
    .map((id) => yardPlants.find((plant) => plant.id === id)?.name)
    .filter(Boolean)
    .join(", ");
}
